#ifndef __AST_TYPE_H__
#define __AST_TYPE_H__

enum ASTType {
    AST_PROTO,
    AST_PROTO_DECL,
    AST_ENDIAN,
    AST_PROTO_DETAILS,
    AST_DISSECTOR_ENTRY,
    AST_DISSECTOR_TABLE,
    AST_ENUM,
    AST_ENUM_BODY_DECL,
    AST_ENUM_BODY_DEFAULT,
    AST_STRUCT,
    AST_STRUCT_BODY_LOCAL,
    AST_STRUCT_BODY_SWITCH,
    AST_LOCAL_ELEMENT,
    AST_SWITCH,
    AST_SWITCH_CONDITION,
    AST_FIELD_PATH,
    AST_FIELD,
    AST_CASE,
    AST_CASE_LABEL,
    AST_CASE_BODY
};

#endif
